import { Item, User, TradePost, ItemRarity } from "./types";

// Mock items with different rarities - Plants and Fruits
export const mockItems: Item[] = [
  // Common items
  {
    id: "1",
    name: "Carrot",
    rarity: "common",
    image: "/placeholder.svg",
    category: "Vegetables",
    description: "A basic orange root vegetable",
    value: 10,
  },
  {
    id: "2",
    name: "Strawberry",
    rarity: "common",
    image: "/placeholder.svg",
    category: "Fruits",
    description: "A sweet red berry",
    value: 15,
  },

  // Uncommon items
  {
    id: "3",
    name: "Blueberry",
    rarity: "uncommon",
    image: "/placeholder.svg",
    category: "Fruits",
    description: "Small blue antioxidant-rich berries",
    value: 25,
  },
  {
    id: "4",
    name: "Manuka Flower",
    rarity: "uncommon",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "Rare flower with healing properties",
    value: 40,
  },
  {
    id: "5",
    name: "Orange Tulip",
    rarity: "uncommon",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "A vibrant orange tulip",
    value: 35,
  },
  {
    id: "6",
    name: "Rose",
    rarity: "uncommon",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "A classic red rose",
    value: 45,
  },
  {
    id: "7",
    name: "Lavender",
    rarity: "uncommon",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "Fragrant purple flowers",
    value: 50,
  },
  {
    id: "8",
    name: "Crocus",
    rarity: "uncommon",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "Early spring flowering bulb",
    value: 30,
  },

  // Rare items
  {
    id: "9",
    name: "Tomato",
    rarity: "rare",
    image: "/placeholder.svg",
    category: "Vegetables",
    description: "Juicy red fruit vegetable",
    value: 80,
  },
  {
    id: "10",
    name: "Corn",
    rarity: "rare",
    image: "/placeholder.svg",
    category: "Vegetables",
    description: "Golden kernels on a cob",
    value: 75,
  },
  {
    id: "11",
    name: "Dandelion",
    rarity: "rare",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "Bright yellow wildflower",
    value: 85,
  },
  {
    id: "12",
    name: "Daffodil",
    rarity: "rare",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "Bright yellow spring flower",
    value: 90,
  },
  {
    id: "13",
    name: "Nectarshade",
    rarity: "rare",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "Mysterious nectar-producing flower",
    value: 120,
  },
  {
    id: "14",
    name: "Raspberry",
    rarity: "rare",
    image: "/placeholder.svg",
    category: "Fruits",
    description: "Sweet-tart red berries",
    value: 100,
  },
  {
    id: "15",
    name: "Foxglove",
    rarity: "rare",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "Tall spikes of tubular flowers",
    value: 110,
  },
  {
    id: "16",
    name: "Succulent",
    rarity: "rare",
    image: "/placeholder.svg",
    category: "Plants",
    description: "Water-storing desert plant",
    value: 95,
  },
  {
    id: "17",
    name: "Bee Balm",
    rarity: "rare",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "Aromatic flower that attracts bees",
    value: 105,
  },
  {
    id: "18",
    name: "Pear",
    rarity: "rare",
    image: "/placeholder.svg",
    category: "Fruits",
    description: "Sweet, teardrop-shaped fruit",
    value: 115,
  },

  // Legendary items
  {
    id: "19",
    name: "Watermelon",
    rarity: "legendary",
    image: "/placeholder.svg",
    category: "Fruits",
    description: "Large, juicy summer fruit",
    value: 300,
  },
  {
    id: "20",
    name: "Pumpkin",
    rarity: "legendary",
    image: "/placeholder.svg",
    category: "Vegetables",
    description: "Large orange gourd",
    value: 280,
  },
  {
    id: "21",
    name: "Apple",
    rarity: "legendary",
    image: "/placeholder.svg",
    category: "Fruits",
    description: "Crisp, sweet fruit of knowledge",
    value: 320,
  },
  {
    id: "22",
    name: "Bamboo",
    rarity: "legendary",
    image: "/placeholder.svg",
    category: "Plants",
    description: "Fast-growing woody grass",
    value: 350,
  },
  {
    id: "23",
    name: "Lilac",
    rarity: "legendary",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "Fragrant purple spring flowers",
    value: 330,
  },
  {
    id: "24",
    name: "Lumira",
    rarity: "legendary",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "Glowing mystical flower",
    value: 400,
  },
  {
    id: "25",
    name: "Violet Corn",
    rarity: "legendary",
    image: "/placeholder.svg",
    category: "Vegetables",
    description: "Rare purple variety of corn",
    value: 380,
  },
  {
    id: "26",
    name: "Nectar Thorn",
    rarity: "legendary",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "Thorny plant with sweet nectar",
    value: 420,
  },

  // Mythical items
  {
    id: "27",
    name: "Coconut",
    rarity: "mythical",
    image: "/placeholder.svg",
    category: "Fruits",
    description: "Tropical fruit with hard shell",
    value: 600,
  },
  {
    id: "28",
    name: "Cactus",
    rarity: "mythical",
    image: "/placeholder.svg",
    category: "Plants",
    description: "Desert plant with water storage",
    value: 580,
  },
  {
    id: "29",
    name: "Dragon Fruit",
    rarity: "mythical",
    image: "/placeholder.svg",
    category: "Fruits",
    description: "Exotic fruit with dragon-like skin",
    value: 750,
  },
  {
    id: "30",
    name: "Honeysuckle",
    rarity: "mythical",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "Sweet-scented climbing vine",
    value: 650,
  },
  {
    id: "31",
    name: "Mango",
    rarity: "mythical",
    image: "/placeholder.svg",
    category: "Fruits",
    description: "Tropical stone fruit",
    value: 680,
  },
  {
    id: "32",
    name: "Nectarine",
    rarity: "mythical",
    image: "/placeholder.svg",
    category: "Fruits",
    description: "Smooth-skinned peach variety",
    value: 620,
  },
  {
    id: "33",
    name: "Peach",
    rarity: "mythical",
    image: "/placeholder.svg",
    category: "Fruits",
    description: "Fuzzy stone fruit",
    value: 640,
  },
  {
    id: "34",
    name: "Pineapple",
    rarity: "mythical",
    image: "/placeholder.svg",
    category: "Fruits",
    description: "Spiky tropical fruit",
    value: 700,
  },
  {
    id: "35",
    name: "Pink Lily",
    rarity: "mythical",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "Elegant pink water lily",
    value: 720,
  },
  {
    id: "36",
    name: "Purple Dahila",
    rarity: "mythical",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "Large purple ornamental flower",
    value: 690,
  },
  {
    id: "37",
    name: "Bendboo",
    rarity: "mythical",
    image: "/placeholder.svg",
    category: "Plants",
    description: "Flexible magical bamboo variant",
    value: 780,
  },
  {
    id: "38",
    name: "Suncoil",
    rarity: "mythical",
    image: "/placeholder.svg",
    category: "Plants",
    description: "Plant that coils toward the sun",
    value: 760,
  },
  {
    id: "39",
    name: "Cocovine",
    rarity: "mythical",
    image: "/placeholder.svg",
    category: "Plants",
    description: "Vine that produces coconuts",
    value: 800,
  },

  // Divine items
  {
    id: "40",
    name: "Grape",
    rarity: "divine",
    image: "/placeholder.svg",
    category: "Fruits",
    description: "Sacred fruit of the gods",
    value: 1200,
  },
  {
    id: "41",
    name: "Mushroom",
    rarity: "divine",
    image: "/placeholder.svg",
    category: "Fungi",
    description: "Divine fungal growth",
    value: 1100,
  },
  {
    id: "42",
    name: "Pepper",
    rarity: "divine",
    image: "/placeholder.svg",
    category: "Vegetables",
    description: "Spicy divine vegetable",
    value: 1300,
  },
  {
    id: "43",
    name: "Cacao",
    rarity: "divine",
    image: "/placeholder.svg",
    category: "Seeds",
    description: "Divine chocolate bean",
    value: 1400,
  },
  {
    id: "44",
    name: "Hive Fruit",
    rarity: "divine",
    image: "/placeholder.svg",
    category: "Fruits",
    description: "Fruit that buzzes with energy",
    value: 1350,
  },
  {
    id: "45",
    name: "Sunflower",
    rarity: "divine",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "Towering flower that follows the sun",
    value: 1250,
  },
  {
    id: "46",
    name: "Dragon Pepper",
    rarity: "divine",
    image: "/placeholder.svg",
    category: "Vegetables",
    description: "Fiery pepper with dragon essence",
    value: 1500,
  },

  // Prismatic items
  {
    id: "47",
    name: "Beanstalk",
    rarity: "prismatic",
    image: "/placeholder.svg",
    category: "Plants",
    description: "Magical stalk that reaches the clouds",
    value: 5000,
  },
  {
    id: "48",
    name: "Ember Lily",
    rarity: "prismatic",
    image: "/placeholder.svg",
    category: "Flowers",
    description: "Flower that burns with eternal flame",
    value: 4500,
  },
  {
    id: "49",
    name: "Sugar Apple",
    rarity: "prismatic",
    image: "/placeholder.svg",
    category: "Fruits",
    description: "Crystalline fruit of pure sweetness",
    value: 6000,
  },
];

// Mock users
export const mockUsers: User[] = [
  {
    id: "1",
    username: "DragonSlayer99",
    displayName: "Dragon Slayer",
    avatar: "/placeholder.svg",
    robloxId: "roblox_123456",
    joinDate: new Date("2023-01-15"),
    isOnline: true,
    stats: {
      totalTrades: 156,
      successfulTrades: 142,
      rating: 4.8,
      totalReviews: 89,
    },
  },
  {
    id: "2",
    username: "MagicCollector",
    displayName: "Magic Collector",
    avatar: "/placeholder.svg",
    robloxId: "roblox_789012",
    joinDate: new Date("2023-03-22"),
    isOnline: false,
    stats: {
      totalTrades: 73,
      successfulTrades: 68,
      rating: 4.6,
      totalReviews: 45,
    },
  },
  {
    id: "3",
    username: "SwordMaster2024",
    displayName: "Sword Master",
    avatar: "/placeholder.svg",
    robloxId: "roblox_345678",
    joinDate: new Date("2024-01-10"),
    isOnline: true,
    stats: {
      totalTrades: 234,
      successfulTrades: 218,
      rating: 4.9,
      totalReviews: 167,
    },
  },
  {
    id: "4",
    username: "NoobTrader",
    displayName: "Rookie Trader",
    avatar: "/placeholder.svg",
    robloxId: "roblox_901234",
    joinDate: new Date("2024-02-01"),
    isOnline: true,
    stats: {
      totalTrades: 12,
      successfulTrades: 10,
      rating: 4.2,
      totalReviews: 8,
    },
  },
  {
    id: "5",
    username: "LegendHunter",
    displayName: "Legend Hunter",
    avatar: "/placeholder.svg",
    robloxId: "roblox_567890",
    joinDate: new Date("2023-06-15"),
    isOnline: false,
    stats: {
      totalTrades: 89,
      successfulTrades: 82,
      rating: 4.7,
      totalReviews: 56,
    },
  },
];

// No pre-made trade posts - users will create their own

export const getRarityColor = (rarity: ItemRarity): string => {
  const rarityColors = {
    common: "text-rarity-common",
    uncommon: "text-rarity-uncommon",
    rare: "text-rarity-rare",
    legendary: "text-rarity-legendary",
    mythical: "text-rarity-mythic",
    divine: "text-rarity-divine",
    prismatic: "text-rarity-prismatic",
  };
  return rarityColors[rarity];
};

export const getRarityBorder = (rarity: ItemRarity): string => {
  const rarityBorders = {
    common: "border-rarity-common",
    uncommon: "border-rarity-uncommon",
    rare: "border-rarity-rare",
    legendary: "border-rarity-legendary",
    mythical: "border-rarity-mythic",
    divine: "border-rarity-divine",
    prismatic: "border-rarity-prismatic",
  };
  return rarityBorders[rarity];
};

export const getRarityGradient = (rarity: ItemRarity): string => {
  const rarityGradients = {
    common: "bg-rarity-common",
    uncommon: "bg-rarity-uncommon",
    rare: "bg-rarity-rare",
    legendary: "bg-rarity-legendary",
    mythical: "bg-rarity-mythic",
    divine: "bg-rarity-divine",
    prismatic: "bg-rarity-prismatic",
  };
  return rarityGradients[rarity];
};
